### ISSUE TITLE
About fnt fonts

### ISSUE THREAD

**Issue by wuzhengzheng** [blotspot/garmin-watchface-protomolecule#7]
Hello, I would like to ask what software you use to generate the icon font. The bitmap icon I recently generated with "Glyph Designer" was badly jagged. I was wondering if you have any good ideas?

**Comment by blotspot** [comment]
I use BMFont as suggested on the Garmin developer page, [here](https://developer.garmin.com/connect-iq/connect-iq-faq/how-do-i-use-custom-fonts/). You should be ok if you follow the guide that is linked there as well.

**Comment by wuzhengzheng** [comment]
Thank you very much. I refer to your code to get the body charge. Unfortunately, it failed. May I ask if there is any good way?

**Comment by blotspot** [comment]
Did you set the rights in the manifest?

```
        <iq:permissions>
            <iq:uses-permission id="SensorHistory"/>
        </iq:permissions>
```
